# Generated by Django 4.0.3 on 2022-03-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Content',
            new_name='content',
        ),
    ]
