# Generated by Django 4.0.3 on 2022-03-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='mame',
            new_name='name',
        ),
    ]
